insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Nola', 'Glass', 'Stanton LLC', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Neddie', 'Leishman', 'Zboncak, Hackett and Ebert', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Man', 'Frobisher', 'Larkin-Beier', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Webb', 'Jery', 'Lebsack Group', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Ossie', 'Scrimshaw', 'Leffler, Marvin and Daniel', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Corabella', 'Hoofe', 'Kiehn, Kozey and Hodkiewicz', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Walt', 'McIndoe', 'Lang, Huels and Crist', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Kris', 'Pugh', 'Mitchell-Kuhn', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Larisa', 'Kernoghan', 'Willms-Kassulke', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jacinda', 'Mitskevich', 'Emard-Feest', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Carlynn', 'Zavattiero', 'O''Conner LLC', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Carlyle', 'Domanek', 'Pouros-Hettinger', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jobi', 'Dougan', 'Swaniawski Group', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Rhoda', 'Lind', 'Flatley, Senger and Haag', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Currie', 'Bain', 'O''Reilly, Klocko and King', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Melloney', 'Iannello', 'Lockman Inc', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Jasun', 'Bell', 'Wolff-Schuster', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Dulcea', 'Barkworth', 'Metz and Sons', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Allen', 'Trosdall', 'Schamberger, Parker and Gutkowski', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Dugald', 'McLarty', 'Torp, Barrows and Botsford', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Martha', 'Worthing', 'Roob Inc', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Neila', 'Cubbinelli', 'O''Keefe, Lueilwitz and Rosenbaum', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Belita', 'Conklin', 'Kertzmann Inc', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Gan', 'Lambertson', 'Luettgen, Romaguera and Douglas', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Stanislaus', 'Gaze', 'Leannon, Rempel and Sipes', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Shea', 'Smorthit', 'Jacobs Group', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Cora', 'Puden', 'Senger-Jenkins', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Bear', 'Dennistoun', 'Schroeder-Johnston', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Mel', 'Heppner', 'Nicolas, Johns and Hills', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Issi', 'Bourgeois', 'Runolfsdottir, Glover and Daniel', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Zachery', 'Trevillion', 'Thompson and Sons', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Jonathan', 'O''Fairy', 'O''Keefe LLC', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Emelita', 'Corking', 'Rath-Shanahan', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Cornelia', 'Hunston', 'Powlowski, Roberts and Hane', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Zarah', 'McAlinion', 'Conn, Hackett and Langworth', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Marje', 'Missenden', 'Ledner-Runolfsdottir', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Cherilynn', 'Seson', 'Ledner LLC', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Gus', 'McComiskie', 'O''Reilly, Conn and Paucek', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Clio', 'Kramer', 'Veum, Funk and Stiedemann', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Janaya', 'Denkin', 'Kozey, Nikolaus and Von', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Sydelle', 'Patchett', 'Romaguera-O''Connell', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Louie', 'Lusk', 'Leuschke and Sons', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Angelo', 'LLelweln', 'Crooks, Barrows and Mosciski', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Berkeley', 'Rudland', 'Renner-King', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Meridith', 'Albin', 'Stamm-Kuhn', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Maurine', 'Klimkovich', 'Okuneva, Heidenreich and Halvorson', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Gasparo', 'Stuffins', 'Little-Stroman', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Zacharie', 'Synnot', 'DuBuque, Mosciski and Bauch', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Tudor', 'Delyth', 'Treutel-Zemlak', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Wakefield', 'Mitchelhill', 'Schaden Group', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jemmie', 'Perrin', 'Kulas-Kohler', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Lennie', 'Risely', 'Kessler, Fritsch and Harber', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Lesya', 'Duddle', 'Klocko, Metz and Goodwin', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jo-anne', 'Dall', 'Runolfsdottir, Hamill and Nader', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Kaila', 'Tierney', 'Howe, Davis and Nolan', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Glennie', 'Lambden', 'Hickle Group', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Waldo', 'Phare', 'Simonis, Feest and Fadel', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Cosmo', 'Jeannot', 'Walker LLC', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Cecily', 'Gebbe', 'Klocko Group', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Isak', 'McEvon', 'White-Crist', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Towney', 'Campione', 'Donnelly, Yundt and O''Conner', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Lucius', 'Gilson', 'Orn LLC', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Damita', 'Yushin', 'Bogan and Sons', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Ardine', 'Leith-Harvey', 'Runolfsson-Konopelski', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Nikolas', 'Fahy', 'Gerhold, Anderson and Padberg', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Scarface', 'McCoughan', 'Bergnaum Group', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Ben', 'Aleksashin', 'Hagenes LLC', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Ritchie', 'Bing', 'Hettinger, Reichel and Collier', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Lorilee', 'Tawse', 'Dickinson-Kuvalis', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jenny', 'Shrimpling', 'Auer Inc', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Stafani', 'Prestland', 'Stanton-Reichel', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Nataline', 'Oulet', 'Roberts-Ritchie', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Rosabel', 'Jirzik', 'Abernathy-Spencer', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jenni', 'Imesson', 'Glover, Swaniawski and Jacobi', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Westleigh', 'Shapcott', 'Carroll LLC', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Chen', 'Maddock', 'Toy, Bruen and Becker', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jo', 'Archbell', 'Roberts-Beatty', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Vivianne', 'Di Maria', 'O''Keefe, Schamberger and Leffler', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Stephani', 'Janak', 'Walker-Connelly', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Alfons', 'Naire', 'Wisoky, Schamberger and Turcotte', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Noach', 'Dumbrall', 'Bernhard, Homenick and Boyle', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Emalee', 'Bootton', 'Luettgen LLC', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Gerri', 'Order', 'Rogahn, Baumbach and Pouros', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Gordie', 'Roseborough', 'Hagenes, Waelchi and Langosh', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Betta', 'Hawsby', 'Cummerata Inc', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Charyl', 'Gruby', 'Rau, Bins and Schiller', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Patsy', 'Dorricott', 'Padberg LLC', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Corey', 'Skirlin', 'Douglas-Fadel', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Tammie', 'Weedenburg', 'Mante-Hauck', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jarrod', 'Abade', 'Lemke LLC', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jean', 'Cureton', 'Huel, Schiller and Ruecker', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Otes', 'Chupin', 'Welch, Mohr and Hammes', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Danielle', 'Simla', 'Yundt, Dickinson and Von', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Marylin', 'Pavier', 'Becker, Cruickshank and D''Amore', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Nicholle', 'Quillinane', 'Casper Group', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Gabriel', 'Penswick', 'Doyle, Deckow and Hermiston', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Corinne', 'Croyden', 'Larkin, Lang and Smitham', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Gerladina', 'Dulieu', 'Bins-Pfannerstill', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Benito', 'Ygo', 'Blick, Kihn and Raynor', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Tracy', 'Durrand', 'Johnson and Sons', 'Product Management');