insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Ainsley', 'Solomonides', 'Temp', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Jori', 'Ailward', 'Temp', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Goldie', 'Brash', 'Rank', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Bartel', 'Burleton', 'Ronstring', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Logan', 'Moden', 'Sonair', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Audrie', 'Apted', 'Lotstring', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Gerald', 'Perdue', 'Bytecard', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Corene', 'Christal', 'Y-Solowarm', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Noby', 'Leglise', 'Treeflex', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Haley', 'Carl', 'Flexidy', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Dynah', 'Huntington', 'Tresom', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Eustace', 'Bristo', 'Subin', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Ema', 'Plant', 'Pannier', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Eddi', 'Vidgeon', 'Fix San', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Rica', 'Weaben', 'Kanlam', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Boot', 'Snarr', 'Gembucket', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Aldwin', 'Gaspar', 'Tresom', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Chris', 'Medendorp', 'Tres-Zap', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Darwin', 'Priestland', 'Cardguard', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Ambros', 'Wisher', 'Andalax', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Dominique', 'McTavy', 'Konklab', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Wallie', 'Kenworthey', 'Alpha', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Desdemona', 'Sutterfield', 'Andalax', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Andris', 'Hinckesman', 'Home Ing', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Thomasin', 'Bailie', 'Tresom', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Mark', 'Warre', 'Bitwolf', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Sansone', 'Gable', 'Tempsoft', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Diane', 'Tunnow', 'Prodder', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Kennie', 'Asey', 'Y-find', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Nelie', 'Edens', 'Flexidy', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Etti', 'Bodker', 'Subin', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Simonne', 'Tuckwood', 'Fix San', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Ram', 'Trynor', 'Overhold', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Abbie', 'Wombwell', 'Matsoft', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Adriena', 'Veeler', 'Cardguard', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Wolf', 'Goodsell', 'Zathin', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Randi', 'Greenslade', 'Tres-Zap', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Saundra', 'Blague', 'Zaam-Dox', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Paxon', 'Kestin', 'Home Ing', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Curry', 'Morrell', 'Trippledex', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Ingra', 'Menco', 'Matsoft', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Merrily', 'Jakubovics', 'Rank', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Kelsey', 'Van Rembrandt', 'Stim', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Temp', 'Godilington', 'Trippledex', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Josselyn', 'Mebius', 'Stronghold', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Lucinda', 'Daice', 'Bytecard', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Con', 'Drissell', 'Temp', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Crichton', 'Delhanty', 'Cardguard', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Hubie', 'Witts', 'Rank', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Bernadene', 'Lowre', 'Overhold', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Oralie', 'Patching', 'Vagram', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Sutton', 'Farnorth', 'Zoolab', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Benyamin', 'Axtonne', 'Fixflex', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Edlin', 'Chatto', 'Voyatouch', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Maurise', 'Heddan', 'Quo Lux', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Tiertza', 'Egre', 'Holdlamis', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Thorndike', 'Guillou', 'Rank', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Manuel', 'Kilfeather', 'Prodder', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Marilee', 'Drury', 'Viva', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Garik', 'Gallant', 'Domainer', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Stormie', 'Corthes', 'Kanlam', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Conni', 'Stirrip', 'Tres-Zap', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Olivia', 'Jonczyk', 'Asoka', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Gayle', 'Ransome', 'Bigtax', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Salli', 'Hattam', 'Hatity', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Laurena', 'Covert', 'Tresom', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Loralee', 'Mandres', 'Domainer', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Renae', 'McGookin', 'Bitchip', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Kellsie', 'Slark', 'Daltfresh', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Lavinie', 'Upwood', 'Alpha', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Dot', 'Kose', 'Sonsing', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Aleece', 'Van Der Hoog', 'Stringtough', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Stephanus', 'D''Oyly', 'Flexidy', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Wendell', 'Spalding', 'Toughjoyfax', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Raynor', 'Flello', 'Y-find', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Andrea', 'Sottell', 'Tampflex', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Terrance', 'Ashe', 'Trippledex', 'Services');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Norah', 'Lisamore', 'Vagram', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Rosene', 'Zuan', 'Cardguard', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Melisse', 'Stoke', 'Veribet', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Monah', 'Kloss', 'Voltsillam', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Jessey', 'Knowlden', 'Fix San', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Ambros', 'McDowell', 'Toughjoyfax', 'Support');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Salli', 'Kainz', 'Hatity', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Ruperto', 'Sedcole', 'Duobam', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Kinna', 'Raun', 'Bytecard', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Rozele', 'Sumbler', 'Trippledex', 'Product Management');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Hedy', 'Frew', 'Duobam', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Myranda', 'Mottinelli', 'Solarbreeze', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Lucila', 'Klyn', 'Stronghold', 'Business Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Wash', 'Oxenham', 'Cookley', 'Engineering');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Seumas', 'Frammingham', 'Alphazap', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Lilah', 'Peaurt', 'Keylex', 'Training');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Antin', 'Oakey', 'Sub-Ex', 'Sales');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Iseabal', 'Winteringham', 'Ventosanzap', 'Accounting');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Finley', 'Peachment', 'Viva', 'Marketing');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Marco', 'Simioli', 'Zontrax', 'Research and Development');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Clea', 'Dripp', 'Fix San', 'Legal');
insert into part2.client (status, first_name, last_name, organization, description) values (false, 'Lucian', 'Brumble', 'It', 'Human Resources');
insert into part2.client (status, first_name, last_name, organization, description) values (true, 'Rheta', 'Gales', 'Redhold', 'Product Management');