insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Sheffie', 'Furman', 'Graphic Interface', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Rog', 'Andrzejczak', 'hardware', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Keely', 'Sutcliffe', 'orchestration', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Elnar', 'Klimpt', 'software', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Lorna', 'Fripps', 'real-time', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Krystalle', 'Baggiani', 'utilisation', 7, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Aloisia', 'Filippello', 'Realigned', 4, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Quent', 'Peeters', 'real-time', 4, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Brok', 'Teresia', 'tangible', 6, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Willabella', 'Midson', 'solution', 4, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Hilarius', 'Lacotte', 'Intuitive', 3, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Emmalyn', 'Jansey', 'projection', 4, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Maryl', 'Boothman', 'middleware', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Sylvan', 'Wadworth', '3rd generation', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Noami', 'Georger', 'complexity', 7, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Elihu', 'Avrashin', 'Persistent', 6, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Rosana', 'Jonathon', 'artificial intelligence', 8, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Myrvyn', 'Lakeland', 'explicit', 9, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Orren', 'Fallen', 'Operative', 1, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Derick', 'Shadwick', 'disintermediate', 1, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Marinna', 'Januszkiewicz', 'User-centric', 2, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Gilda', 'Trevor', 'disintermediate', 2, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Hollyanne', 'Craggs', 'Robust', 6, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Jaquith', 'Barrowcliff', 'moderator', 4, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Page', 'Wilmington', 'cohesive', 6, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Gipsy', 'Ledur', 'Front-line', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Priscilla', 'Bonifacio', 'national', 6, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Peta', 'Wybourne', 'didactic', 8, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Sydney', 'Heys', 'Quality-focused', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Marta', 'Netherclift', 'asymmetric', 1, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Charissa', 'Duxbury', 'Optimized', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Nester', 'Shreeves', 'definition', 4, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Pascale', 'Jorgensen', '5th generation', 8, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Lynette', 'Baskerville', 'Customizable', 1, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Galen', 'Lidgey', 'workforce', 2, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Tracy', 'Bullas', 'customer loyalty', 1, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Antonia', 'Arstingall', 'didactic', 2, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Nikola', 'Ellcome', 'Multi-tiered', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Chery', 'Acton', 'Multi-lateral', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Brandais', 'Durtnal', 'clear-thinking', 10, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Annice', 'Lancley', 'neural-net', 4, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Hannie', 'Lyfield', 'extranet', 2, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Hercule', 'Pettko', 'Distributed', 2, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Dall', 'Dinis', 'Stand-alone', 1, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Aggie', 'Tincknell', 'Integrated', 3, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Jolynn', 'Fogel', 'Visionary', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ariela', 'Guidoni', 'neural-net', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Bertie', 'Grishinov', 'asynchronous', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Curcio', 'L''oiseau', 'Synergized', 6, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Tadeo', 'Woodcroft', 'regional', 10, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Leland', 'Borrel', 'context-sensitive', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Emmi', 'Florez', '5th generation', 4, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Moses', 'Housbey', 'Ergonomic', 3, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Dermot', 'Fust', 'Ergonomic', 9, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ernst', 'Massei', 'Programmable', 4, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Barnaby', 'Van der Son', 'upward-trending', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Charlene', 'Carbin', 'attitude', 4, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Vilhelmina', 'Messer', 'mission-critical', 1, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ricki', 'Tie', 'foreground', 8, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Carroll', 'Bellwood', 'strategy', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Jacques', 'Treneer', 'empowering', 1, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Bobette', 'Kenzie', 'Programmable', 1, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Annecorinne', 'McConnal', 'Cloned', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Nataline', 'Autin', 'Fully-configurable', 2, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Herc', 'Fippe', 'Mandatory', 8, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Myrilla', 'Yoxall', 'Right-sized', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Joelynn', 'Pirie', 'local', 10, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Blake', 'Dewan', 'Exclusive', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ellary', 'Gillis', 'Open-architected', 2, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Barny', 'Fairbrace', 'directional', 6, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Homer', 'Bolens', 'intermediate', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Charleen', 'Thorold', 'leading edge', 6, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Free', 'Iwaszkiewicz', 'system-worthy', 2, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Crichton', 'Hudson', 'Mandatory', 9, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Burch', 'Felgat', 'moderator', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Emalia', 'Domenico', 'leading edge', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Erwin', 'Doorly', 'Ameliorated', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Otha', 'Brunini', 'Innovative', 1, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Trev', 'Forsdike', 'implementation', 4, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Willis', 'Jankowski', 'hardware', 1, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Lenette', 'Fiddy', 'monitoring', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Mona', 'Delhanty', 'forecast', 2, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Harri', 'Pedler', 'neural-net', 1, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Georgeanne', 'Kirrage', 'secured line', 2, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Cyrus', 'Windrus', 'time-frame', 7, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Justino', 'Sargint', 'national', 6, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Lesli', 'Irwin', 'Balanced', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Cindra', 'Schwander', 'Focused', 6, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ingrim', 'Bozworth', 'Streamlined', 1, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Esmeralda', 'Pawson', 'Pre-emptive', 4, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Vita', 'Tewnion', 'toolset', 6, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Morse', 'Filgate', 'structure', 6, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Alessandro', 'Webland', 'global', 9, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Otho', 'Trail', 'matrix', 3, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Georgianne', 'Hymus', 'Optimized', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Josie', 'Koppeck', 'middleware', 7, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Constantin', 'Joule', 'interactive', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Chloette', 'Acock', 'multimedia', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Bebe', 'Donegan', 'Total', 2, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Milly', 'Mougenel', 'Multi-lateral', 5, 1);