insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Monte', 'Gunston', 'orchestration', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Elnar', 'Gretton', 'Adaptive', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Adara', 'Franies', 'support', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Osborne', 'Sainz', 'capability', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Patrica', 'Paxforde', 'Profit-focused', 7, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Trish', 'Whiting', 'frame', 4, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Fanny', 'Roberson', 'throughput', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Pat', 'Crebo', 'function', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Alyson', 'Heijnen', 'Focused', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Merry', 'Janoschek', 'Optimized', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ruggiero', 'Sivill', 'Universal', 10, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ancell', 'Innman', 'benchmark', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Donn', 'Thaine', 'leverage', 10, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Nataniel', 'Sands-Allan', 'next generation', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Darci', 'Paddle', 'context-sensitive', 6, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Wernher', 'Muddicliffe', 'Optional', 4, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Allis', 'Haslum', 'challenge', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Mendie', 'Lesslie', 'Fundamental', 8, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Law', 'Khristyukhin', 'Down-sized', 8, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Adan', 'Blaxter', 'solution-oriented', 9, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Lucretia', 'Ouldcott', 'grid-enabled', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Mike', 'Carnson', 'Profit-focused', 8, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Collie', 'McReidy', 'Universal', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Alwin', 'Quidenham', 'knowledge user', 10, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Saunder', 'Thing', 'hierarchy', 8, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Kelby', 'Whartonby', 'analyzer', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Barbe', 'Larroway', 'Team-oriented', 8, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Rollie', 'Corrin', 'artificial intelligence', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Star', 'Sturgeon', 'definition', 4, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Lindy', 'Saurin', 'local', 4, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Luciano', 'Yurocjkin', 'holistic', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Caroljean', 'Flatt', 'Programmable', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Giselbert', 'Tight', 'Proactive', 6, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Gwenora', 'Grizard', 'hybrid', 10, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Jean', 'Phillpot', 'zero defect', 4, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Sophi', 'Redler', 'attitude-oriented', 10, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Mercedes', 'Kimblin', 'portal', 6, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Merill', 'Batrip', 'Persistent', 8, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Templeton', 'Ruggiero', 'Implemented', 10, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Cyrill', 'Keuntje', 'content-based', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Tyrone', 'Langrick', 'Switchable', 7, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Rayner', 'Ockleshaw', 'Up-sized', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Edvard', 'Limerick', 'Fully-configurable', 4, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Romy', 'Bunny', 'User-centric', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Miguel', 'Brimilcome', 'Ergonomic', 10, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Warner', 'Silvermann', 'task-force', 6, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ced', 'Farrans', 'non-volatile', 6, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Corny', 'Hurst', 'foreground', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Sephira', 'Bridden', 'knowledge user', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Jolynn', 'Symones', 'groupware', 8, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Tracie', 'Coye', 'encompassing', 4, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Aube', 'Broadnicke', 'website', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Ferdinanda', 'Meadus', 'Public-key', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Byron', 'Kitchenman', 'parallelism', 4, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Chet', 'Hatrick', 'Up-sized', 5, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Belva', 'Shanks', 'hierarchy', 9, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Thorvald', 'Anthoney', 'flexibility', 6, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Madlen', 'McWhannel', 'fault-tolerant', 6, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Murial', 'Butner', 'maximized', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Barnaby', 'Seton', 'installation', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Frank', 'Ruggier', '24 hour', 10, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Constantia', 'Mulvy', 'project', 7, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Justino', 'Kattenhorn', 'strategy', 10, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Devland', 'Yakubov', 'Graphic Interface', 9, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Tedda', 'Wartnaby', 'productivity', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Cherri', 'Hickinbottom', 'zero administration', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Peg', 'Mathieu', 'Cross-platform', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Worth', 'Abrahmovici', 'Expanded', 10, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Esmeralda', 'Cordero', 'encompassing', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Annelise', 'Ballintyne', 'Synchronised', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Nappie', 'Goodban', 'holistic', 7, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Cristabel', 'Giacoppoli', 'Assimilated', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Gracie', 'Fritzer', 'Distributed', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Clim', 'Matus', 'optimizing', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Stephine', 'Rice', 'toolset', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Jeniffer', 'Rogeron', 'product', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Felike', 'Loughlin', 'system engine', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Brina', 'Thompstone', 'Robust', 8, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Randie', 'Titmus', 'demand-driven', 9, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Marcellus', 'Kinchlea', 'Distributed', 8, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Brian', 'Duffan', 'Reverse-engineered', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Nadya', 'Pattington', 'coherent', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Hendrick', 'Jorck', 'Phased', 8, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Shelley', 'McKearnen', 'leading edge', 9, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Judie', 'Jorat', 'neural-net', 10, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Milzie', 'Toffaloni', 'task-force', 5, 1);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Rozamond', 'Gownge', 'object-oriented', 4, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Thorstein', 'Arrighetti', 'time-frame', 9, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Deloris', 'Arstingall', 'installation', 5, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Amery', 'Kaye', 'projection', 6, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Nelia', 'Maryan', 'structure', 10, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Aldis', 'Bullick', 'optimizing', 9, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Rhodia', 'Barette', 'dynamic', 7, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Rosemonde', 'McGuane', 'cohesive', 8, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Christel', 'Popworth', 'Cloned', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Angeline', 'Riddich', 'hardware', 8, 4);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Reggie', 'Ashbey', 'multi-tasking', 5, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Catina', 'Symondson', 'toolset', 4, 3);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Worthington', 'Pedroni', 'cohesive', 7, 2);
insert into part2.member (first_name, last_name, title, race_id, rank_id) values ('Cassius', 'Oldman', 'contextually-based', 9, 2);