insert into part2.product (name, cost, description) values ('morbi', '$49.81', 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into part2.product (name, cost, description) values ('eu', '$19.39', 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into part2.product (name, cost, description) values ('consectetuer', '$26.00', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo');
insert into part2.product (name, cost, description) values ('luctus', '$14.41', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus');
insert into part2.product (name, cost, description) values ('nulla', '$29.89', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue');
insert into part2.product (name, cost, description) values ('molestie', '$3.42', 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor');
insert into part2.product (name, cost, description) values ('nullam', '$37.96', 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh');
insert into part2.product (name, cost, description) values ('vitae', '$2.79', 'sit amet cursus id turpis integer aliquet massa id lobortis');
insert into part2.product (name, cost, description) values ('morbi', '$8.23', 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam');
insert into part2.product (name, cost, description) values ('nullam', '$47.21', 'viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit');
insert into part2.product (name, cost, description) values ('dui', '$40.16', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel');
insert into part2.product (name, cost, description) values ('dui', '$10.96', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into part2.product (name, cost, description) values ('ac', '$47.83', 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede');
insert into part2.product (name, cost, description) values ('justo', '$28.35', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque');
insert into part2.product (name, cost, description) values ('etiam', '$43.70', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio');
insert into part2.product (name, cost, description) values ('luctus', '$19.84', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into part2.product (name, cost, description) values ('pede', '$29.42', 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse');
insert into part2.product (name, cost, description) values ('justo', '$16.30', 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into part2.product (name, cost, description) values ('cras', '$15.21', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet');
insert into part2.product (name, cost, description) values ('curae', '$32.29', 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into part2.product (name, cost, description) values ('posuere', '$24.75', 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi');
insert into part2.product (name, cost, description) values ('lorem', '$15.93', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into part2.product (name, cost, description) values ('vestibulum', '$19.49', 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into part2.product (name, cost, description) values ('orci', '$26.29', 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into part2.product (name, cost, description) values ('eget', '$39.44', 'id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet');
insert into part2.product (name, cost, description) values ('semper', '$2.71', 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into part2.product (name, cost, description) values ('fusce', '$34.95', 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor');
insert into part2.product (name, cost, description) values ('amet', '$46.20', 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi');
insert into part2.product (name, cost, description) values ('quisque', '$47.21', 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus');
insert into part2.product (name, cost, description) values ('sem', '$39.55', 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus');
insert into part2.product (name, cost, description) values ('cubilia', '$16.08', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam');
insert into part2.product (name, cost, description) values ('eu', '$48.00', 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum');
insert into part2.product (name, cost, description) values ('tristique', '$5.40', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium');
insert into part2.product (name, cost, description) values ('nullam', '$40.67', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque');
insert into part2.product (name, cost, description) values ('luctus', '$35.65', 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into part2.product (name, cost, description) values ('venenatis', '$15.50', 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into part2.product (name, cost, description) values ('libero', '$37.97', 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius');
insert into part2.product (name, cost, description) values ('donec', '$16.24', 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam');
insert into part2.product (name, cost, description) values ('nisi', '$1.31', 'non mauris morbi non lectus aliquam sit amet diam in');
insert into part2.product (name, cost, description) values ('a', '$31.20', 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into part2.product (name, cost, description) values ('cras', '$36.74', 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut');
insert into part2.product (name, cost, description) values ('faucibus', '$21.03', 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi');
insert into part2.product (name, cost, description) values ('diam', '$4.36', 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea');
insert into part2.product (name, cost, description) values ('sem', '$4.71', 'integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices');
insert into part2.product (name, cost, description) values ('quis', '$27.40', 'sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue');
insert into part2.product (name, cost, description) values ('rutrum', '$47.89', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel');
insert into part2.product (name, cost, description) values ('nascetur', '$18.41', 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat');
insert into part2.product (name, cost, description) values ('fusce', '$28.70', 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into part2.product (name, cost, description) values ('dapibus', '$46.37', 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero');
insert into part2.product (name, cost, description) values ('convallis', '$49.17', 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit');
insert into part2.product (name, cost, description) values ('odio', '$34.25', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl');
insert into part2.product (name, cost, description) values ('cubilia', '$36.71', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in');
insert into part2.product (name, cost, description) values ('orci', '$23.03', 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec');
insert into part2.product (name, cost, description) values ('iaculis', '$19.71', 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede');
insert into part2.product (name, cost, description) values ('eget', '$11.48', 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed');
insert into part2.product (name, cost, description) values ('nulla', '$48.09', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh');
insert into part2.product (name, cost, description) values ('varius', '$4.20', 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at');
insert into part2.product (name, cost, description) values ('interdum', '$44.62', 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac');
insert into part2.product (name, cost, description) values ('fermentum', '$8.30', 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse');
insert into part2.product (name, cost, description) values ('nulla', '$10.44', 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor');
insert into part2.product (name, cost, description) values ('dui', '$47.86', 'ac lobortis vel dapibus at diam nam tristique tortor eu');
insert into part2.product (name, cost, description) values ('nam', '$9.98', 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into part2.product (name, cost, description) values ('vivamus', '$32.45', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet');
insert into part2.product (name, cost, description) values ('gravida', '$14.13', 'id massa id nisl venenatis lacinia aenean sit amet justo');
insert into part2.product (name, cost, description) values ('amet', '$20.56', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla');
insert into part2.product (name, cost, description) values ('lobortis', '$33.92', 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus');
insert into part2.product (name, cost, description) values ('nulla', '$2.78', 'ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into part2.product (name, cost, description) values ('eu', '$9.57', 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus');
insert into part2.product (name, cost, description) values ('ante', '$13.12', 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor');
insert into part2.product (name, cost, description) values ('integer', '$20.65', 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non');
insert into part2.product (name, cost, description) values ('in', '$11.94', 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est');
insert into part2.product (name, cost, description) values ('aliquam', '$1.23', 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into part2.product (name, cost, description) values ('luctus', '$8.05', 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam');
insert into part2.product (name, cost, description) values ('elit', '$13.01', 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia');
insert into part2.product (name, cost, description) values ('congue', '$24.45', 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo');
insert into part2.product (name, cost, description) values ('sapien', '$41.57', 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into part2.product (name, cost, description) values ('id', '$10.84', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in');
insert into part2.product (name, cost, description) values ('quis', '$26.87', 'est quam pharetra magna ac consequat metus sapien ut nunc');
insert into part2.product (name, cost, description) values ('id', '$28.07', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus');
insert into part2.product (name, cost, description) values ('vestibulum', '$40.53', 'mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula');
insert into part2.product (name, cost, description) values ('in', '$6.50', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec');
insert into part2.product (name, cost, description) values ('vel', '$23.41', 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in');
insert into part2.product (name, cost, description) values ('platea', '$28.18', 'eu massa donec dapibus duis at velit eu est congue');
insert into part2.product (name, cost, description) values ('maecenas', '$38.93', 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor');
insert into part2.product (name, cost, description) values ('sapien', '$28.28', 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus');
insert into part2.product (name, cost, description) values ('vel', '$31.97', 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum');
insert into part2.product (name, cost, description) values ('ac', '$30.95', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non');
insert into part2.product (name, cost, description) values ('erat', '$48.62', 'risus auctor sed tristique in tempus sit amet sem fusce');
insert into part2.product (name, cost, description) values ('sed', '$11.24', 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras');
insert into part2.product (name, cost, description) values ('eu', '$34.80', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id');
insert into part2.product (name, cost, description) values ('quis', '$3.56', 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo');
insert into part2.product (name, cost, description) values ('pede', '$30.25', 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget');
insert into part2.product (name, cost, description) values ('vel', '$41.79', 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into part2.product (name, cost, description) values ('lacinia', '$43.52', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra');
insert into part2.product (name, cost, description) values ('eget', '$8.29', 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante');
insert into part2.product (name, cost, description) values ('velit', '$3.53', 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero');
insert into part2.product (name, cost, description) values ('non', '$35.40', 'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into part2.product (name, cost, description) values ('sagittis', '$17.98', 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit');
insert into part2.product (name, cost, description) values ('tempor', '$10.21', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate');
insert into part2.product (name, cost, description) values ('morbi', '$28.51', 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra');