insert into part2.product (name, cost, description) values ('Mushroom - Porcini Frozen', '$23.08', 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into part2.product (name, cost, description) values ('Island Oasis - Lemonade', '$31.51', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat');
insert into part2.product (name, cost, description) values ('Glass - Wine, Plastic, Clear 5 Oz', '$14.77', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est');
insert into part2.product (name, cost, description) values ('Anisette - Mcguiness', '$30.36', 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut');
insert into part2.product (name, cost, description) values ('Beets', '$15.92', 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum');
insert into part2.product (name, cost, description) values ('Maintenance Removal Charge', '$33.48', 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui');
insert into part2.product (name, cost, description) values ('Scallops - In Shell', '$5.90', 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus');
insert into part2.product (name, cost, description) values ('Veal - Osso Bucco', '$19.02', 'eleifend pede libero quis orci nullam molestie nibh in lectus');
insert into part2.product (name, cost, description) values ('Longos - Grilled Veg Sandwiches', '$18.09', 'ut odio cras mi pede malesuada in imperdiet et commodo');
insert into part2.product (name, cost, description) values ('Cheese - Ermite Bleu', '$10.83', 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam');
insert into part2.product (name, cost, description) values ('Asparagus - Green, Fresh', '$39.87', 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in');
insert into part2.product (name, cost, description) values ('Bag Clear 10 Lb', '$20.88', 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into part2.product (name, cost, description) values ('Soup - Knorr, Classic Can. Chili', '$17.22', 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam');
insert into part2.product (name, cost, description) values ('Compound - Raspberry', '$10.38', 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus');
insert into part2.product (name, cost, description) values ('Kellogs Cereal In A Cup', '$29.62', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim');
insert into part2.product (name, cost, description) values ('Wine - Stoneliegh Sauvignon', '$24.75', 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into part2.product (name, cost, description) values ('Bread - Roll, Canadian Dinner', '$19.33', 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien');
insert into part2.product (name, cost, description) values ('Nut - Almond, Blanched, Whole', '$31.17', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi');
insert into part2.product (name, cost, description) values ('Halibut - Whole, Fresh', '$47.13', 'diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum');
insert into part2.product (name, cost, description) values ('Barramundi', '$25.35', 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus');
insert into part2.product (name, cost, description) values ('Muffin Mix - Oatmeal', '$10.05', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel');
insert into part2.product (name, cost, description) values ('Mudslide', '$18.55', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in');
insert into part2.product (name, cost, description) values ('Beef - Rib Roast, Capless', '$34.61', 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a');
insert into part2.product (name, cost, description) values ('Pork - Tenderloin, Fresh', '$47.80', 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat');
insert into part2.product (name, cost, description) values ('Tea - Darjeeling, Azzura', '$41.26', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue');
insert into part2.product (name, cost, description) values ('Lemonade - Black Cherry, 591 Ml', '$8.41', 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio');
insert into part2.product (name, cost, description) values ('Wine - Prosecco Valdobienne', '$20.21', 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec');
insert into part2.product (name, cost, description) values ('Ecolab - Medallion', '$45.45', 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices');
insert into part2.product (name, cost, description) values ('Soup Campbells Split Pea And Ham', '$15.67', 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante');
insert into part2.product (name, cost, description) values ('Chip - Potato Dill Pickle', '$39.32', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus');
insert into part2.product (name, cost, description) values ('Table Cloth 120 Round White', '$17.77', 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac');
insert into part2.product (name, cost, description) values ('Greens Mustard', '$28.94', 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus');
insert into part2.product (name, cost, description) values ('Coconut - Whole', '$18.97', 'nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl');
insert into part2.product (name, cost, description) values ('Wine - Mas Chicet Rose, Vintage', '$19.57', 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into part2.product (name, cost, description) values ('Potato - Sweet', '$9.31', 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec');
insert into part2.product (name, cost, description) values ('Wine - Jafflin Bourgongone', '$21.75', 'mauris vulputate elementum nullam varius nulla facilisi cras non velit');
insert into part2.product (name, cost, description) values ('Artichokes - Jerusalem', '$8.41', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis');
insert into part2.product (name, cost, description) values ('Curry Paste - Green Masala', '$44.32', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean');
insert into part2.product (name, cost, description) values ('Grand Marnier', '$18.38', 'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into part2.product (name, cost, description) values ('Barramundi', '$37.96', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis');
insert into part2.product (name, cost, description) values ('Compound - Raspberry', '$10.37', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent');
insert into part2.product (name, cost, description) values ('Wine - Puligny Montrachet A.', '$14.96', 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem');
insert into part2.product (name, cost, description) values ('Cup - 4oz Translucent', '$6.46', 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros');
insert into part2.product (name, cost, description) values ('Extract Vanilla Pure', '$30.47', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim');
insert into part2.product (name, cost, description) values ('Spinach - Frozen', '$49.69', 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula');
insert into part2.product (name, cost, description) values ('Soap - Mr.clean Floor Soap', '$24.50', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo');
insert into part2.product (name, cost, description) values ('Banana - Leaves', '$42.75', 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo');
insert into part2.product (name, cost, description) values ('Tuna - Sushi Grade', '$45.86', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur');
insert into part2.product (name, cost, description) values ('Lumpfish Black', '$30.47', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in');
insert into part2.product (name, cost, description) values ('Vector Energy Bar', '$2.31', 'in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at');
insert into part2.product (name, cost, description) values ('Clams - Littleneck, Whole', '$9.35', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus');
insert into part2.product (name, cost, description) values ('Jicama', '$14.91', 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum');
insert into part2.product (name, cost, description) values ('Pork - Tenderloin, Frozen', '$3.20', 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare');
insert into part2.product (name, cost, description) values ('Wild Boar - Tenderloin', '$12.98', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut');
insert into part2.product (name, cost, description) values ('Knife Plastic - White', '$48.18', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu');
insert into part2.product (name, cost, description) values ('Ice Cream - Fudge Bars', '$6.76', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique');
insert into part2.product (name, cost, description) values ('Yoplait Drink', '$11.86', 'mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue');
insert into part2.product (name, cost, description) values ('Wine - Chateauneuf Du Pape', '$20.12', 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into part2.product (name, cost, description) values ('Pastry - Carrot Muffin - Mini', '$21.18', 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget');
insert into part2.product (name, cost, description) values ('Soup Knorr Chili With Beans', '$31.18', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into part2.product (name, cost, description) values ('Wine - Sawmill Creek Autumn', '$47.37', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus');
insert into part2.product (name, cost, description) values ('Chocolate Bar - Coffee Crisp', '$38.28', 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget');
insert into part2.product (name, cost, description) values ('Tea - Honey Green Tea', '$26.66', 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in');
insert into part2.product (name, cost, description) values ('Juice - Pineapple, 341 Ml', '$7.87', 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim');
insert into part2.product (name, cost, description) values ('Ecolab - Orange Frc, Cleaner', '$8.81', 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede');
insert into part2.product (name, cost, description) values ('Nougat - Paste / Cream', '$12.68', 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat');
insert into part2.product (name, cost, description) values ('Asparagus - Mexican', '$7.52', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into part2.product (name, cost, description) values ('Butter - Unsalted', '$28.54', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget');
insert into part2.product (name, cost, description) values ('Table Cloth 62x114 Colour', '$37.45', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien');
insert into part2.product (name, cost, description) values ('Nut - Pistachio, Shelled', '$35.71', 'nunc vestibulum ante ipsum primis in faucibus orci luctus et');
insert into part2.product (name, cost, description) values ('Sauce - Ranch Dressing', '$10.98', 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec');
insert into part2.product (name, cost, description) values ('Beef - Tender Tips', '$27.76', 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into part2.product (name, cost, description) values ('Coffee - Beans, Whole', '$47.37', 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula');
insert into part2.product (name, cost, description) values ('Soup - Campbells Beef Noodle', '$1.96', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into part2.product (name, cost, description) values ('Tray - 16in Rnd Blk', '$15.53', 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque');
insert into part2.product (name, cost, description) values ('Soup - Knorr, Veg / Beef', '$32.26', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl');
insert into part2.product (name, cost, description) values ('Vinegar - Red Wine', '$8.35', 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec');
insert into part2.product (name, cost, description) values ('Puree - Kiwi', '$38.82', 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse');
insert into part2.product (name, cost, description) values ('Urban Zen Drinks', '$40.05', 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris');
insert into part2.product (name, cost, description) values ('Mussels - Cultivated', '$30.31', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo');
insert into part2.product (name, cost, description) values ('Sprouts - Peppercress', '$47.37', 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into part2.product (name, cost, description) values ('Chocolate - Compound Coating', '$21.74', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero');
insert into part2.product (name, cost, description) values ('Cardamon Seed / Pod', '$43.21', 'aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra');
insert into part2.product (name, cost, description) values ('Flour - Strong', '$34.46', 'venenatis turpis enim blandit mi in porttitor pede justo eu');
insert into part2.product (name, cost, description) values ('Sprite, Diet - 355ml', '$14.37', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede');
insert into part2.product (name, cost, description) values ('Wine - Rioja Campo Viejo', '$8.47', 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam');
insert into part2.product (name, cost, description) values ('Soup - Campbells Chili Veg', '$24.45', 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris');
insert into part2.product (name, cost, description) values ('Relish', '$2.10', 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi');
insert into part2.product (name, cost, description) values ('Creme De Banane - Marie', '$38.98', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra');
insert into part2.product (name, cost, description) values ('Slt - Individual Portions', '$11.19', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor');
insert into part2.product (name, cost, description) values ('Beef - Ground Lean Fresh', '$1.00', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis');
insert into part2.product (name, cost, description) values ('Appetizer - Mini Egg Roll, Shrimp', '$28.05', 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta');
insert into part2.product (name, cost, description) values ('Veal - Provimi Inside', '$49.16', 'odio odio elementum eu interdum eu tincidunt in leo maecenas');
insert into part2.product (name, cost, description) values ('Tabasco Sauce, 2 Oz', '$49.49', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue');
insert into part2.product (name, cost, description) values ('Wine - Red, Gamay Noir', '$29.38', 'purus eu magna vulputate luctus cum sociis natoque penatibus et');
insert into part2.product (name, cost, description) values ('Sprouts - Alfalfa', '$29.38', 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros');
insert into part2.product (name, cost, description) values ('Bread - Italian Roll With Herbs', '$15.08', 'quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a');
insert into part2.product (name, cost, description) values ('Plate Pie Foil', '$41.96', 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo');
insert into part2.product (name, cost, description) values ('Rye Special Old', '$28.74', 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at');
insert into part2.product (name, cost, description) values ('Bar Mix - Lemon', '$2.39', 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in');
showing first 100 rows
# Rows: